---
- hosts: mynodess
  become: yes
  tasks:
  - name: I want to install apache2 webserver
    apt:
     name: "{{mypackonubuntu}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: I want to start apache2
    service:
      name: "{{mypackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: I want to install redhat
    dnf:
      name: "{{mypackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"