---
- hosts: rednodes
  become: yes
  tasks:
  - name: I want to install apache2 webserver
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"

  - name: I want to start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"

  - name: I want to install redhat
    dnf:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"